name: UV Pytest CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_lint_test:
    name: Build, Lint, and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv and set up Python 3.13
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"
          enable-cache: true

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run linting
        run: uvx ruff check

      - name: Run tests with pytest
        run: uv pip install -e . && uv run pytest && uv sync
